:: -----------------------------------------------------------------------------------
::   ___                     ____                             ____                  _ 
::  / _ \ _ __   ___ _ __   / ___|  ___ _ ____   _____ _ __  |  _ \ __ _ _ __   ___| |
:: | | | | '_ \ / _ \ '_ \  \___ \ / _ \ '__\ \ / / _ \ '__| | |_) / _` | '_ \ / _ \ |
:: | |_| | |_) |  __/ | | |  ___) |  __/ |   \ V /  __/ |    |  __/ (_| | | | |  __/ |
::  \___/| .__/ \___|_| |_| |____/ \___|_|    \_/ \___|_|    |_|   \__,_|_| |_|\___|_|
::       |_|
::
::                 /|  /|  -----------------------------------------------
::                 ||__||  |                                             |
::                /   O O\__      Do not edit this file, as you will     |
::               /          \        lose your edits the next time       |
::              /      \     \         the module is initialized!        |
::             /   _    \     \                                          |
::            /    |\____\     \------------------------------------------
::           /     | | | |\____/      ||
::          /       \| | | |/ |     __||
::         /  /  \   -------  |_____| ||
::        /   |   |           |       --|
::        |   |   |           |_____  --|
::        |  |_|_|_|          |     \----
::        /\                  |
::       / /\        |        /
::      / /  |       |       |
::  ___/ /   |       |       |
:: |____/    c_c_c_C/ \C_c_c_c
::
:: -----------------------------------------------------------------------------------
if /i "%1"=="resetenv" goto resetenv
set "AUTHENTICATION_KERBEROS_CLIENT_LOG="
set "AUTHENTICATION_LDAP_CLIENT_LOG="
set "AUTHENTICATION_PAM_LOG="
set "DBI_USER="
set "DBI_TRACE="
set "LD_RUN_PATH=E:\Server\OSPanel\modules\MySQL-8.2\lib"
set "LIBMYSQL_PLUGINS="
set "LIBMYSQL_PLUGIN_DIR=E:\Server\OSPanel\modules\MySQL-8.2\lib\plugin"
set "MYSQL_GROUP_SUFFIX="
set "MYSQL_HOME=E:\Server\OSPanel\modules\MySQL-8.2"
set "MYSQL_HOST=MySQL-8.2"
set "MYSQL_PS1="
set "MYSQL_PWD="
set "MYSQL_TCP_PORT=3306"
set "MYSQL_TEST_LOGIN_FILE=E:\Server\OSPanel\data\MySQL-8.2\default\.mylogin.cnf"
set "MYSQL_UNIX_PORT=MySQL-8.2"
set "MYSQLX_TCP_PORT=33060"
if /i not "%1"=="add" set "PATH=E:\Server\OSPanel\bin;E:\Server\OSPanel\modules\MySQL-8.2\bin;%SYSTEMROOT%\system32;%SYSTEMROOT%;%SYSTEMROOT%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0"
if /i "%1"=="add" set "PATH=E:\Server\OSPanel\modules\MySQL-8.2\bin;%PATH%"
set "TEMP=E:\Server\OSPanel\temp\MySQL-8.2\default"
set "TMP=E:\Server\OSPanel\temp\MySQL-8.2\default"
set "TMPDIR=E:\Server\OSPanel\temp\MySQL-8.2\default"
set "TZ=Etc/GMT-3"
set "USER=root"
set "CURL_CA_BUNDLE=E:\Server\OSPanel\data\ssl\cacert.pem"
set "HOME=E:\Server\OSPanel\user"
set "HOMEDRIVE=E:"
set "HOMEPATH=\Server\OSPanel\user"
set "TERM=dumb"
if /i not "65001"=="" if /i not "%1"=="shell" set "OSP_CODEPAGE=65001" & if defined OSP_TMP_CODEPAGE set "OSP_TMP_CODEPAGE=65001"
goto end
:resetenv
set "AUTHENTICATION_KERBEROS_CLIENT_LOG="
set "AUTHENTICATION_LDAP_CLIENT_LOG="
set "AUTHENTICATION_PAM_LOG="
set "DBI_USER="
set "DBI_TRACE="
set "LD_RUN_PATH="
set "LIBMYSQL_PLUGINS="
set "LIBMYSQL_PLUGIN_DIR="
set "MYSQL_GROUP_SUFFIX="
set "MYSQL_HOME="
set "MYSQL_HOST="
set "MYSQL_PS1="
set "MYSQL_PWD="
set "MYSQL_TCP_PORT="
set "MYSQL_TEST_LOGIN_FILE="
set "MYSQL_UNIX_PORT="
set "MYSQLX_TCP_PORT="
set "PATH="
set "TEMP="
set "TMP="
set "TMPDIR="
set "TZ="
set "USER="
set "CURL_CA_BUNDLE="
set "HOME="
set "HOMEDRIVE="
set "HOMEPATH="
set "TERM="
:end
exit /b 0
